<a href="https://colab.research.google.com/github/AldhiHamdani/big-data/blob/main/tugas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

1. melihat version numpy

In [117]:
import numpy
numpy.__version__

'1.19.5'

 Mengimport numpy

In [118]:

import numpy as np

Menampilkan dokumen bawaan numpy

In [119]:
np?


1) UNDERSTANDING DATA TYPES IN PYTHON

di python operasi dapat ditulis sebagai berikut

In [120]:

result = 0
for i in range(100):
 result += i

a. A Python List Is More Than Just a List

1.Menampung multielemen standar yang dapat berubah dalam Python adalah daftar.

In [121]:

L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


melihat tipe data dari indeks ke 0

In [122]:
type(L[0])

int

membuat list string

In [123]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

melihat type data dari indeks ke 0

In [124]:
type(L2[0])

str

membuat daftar heterogen

In [125]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

b. Fixed-Type Arrays in Python

membuat array padat dari tipe seragam:

In [126]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


c. Creating Arrays from Python Lists

membuat array list

In [127]:
#integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

NumPy dibatasi ke array yang semuanya berisi tipe yang sama. Jika jenis tidak cocok, NumPy akan upcast jika memungkinkan (di sini, integer adalah upcast ke floating point):

In [128]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])


mengatur tipe data dari array yang dihasilkan, gunakan dtype

In [129]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)


array NumPy secara eksplisit bisa multidimensi

In [130]:

#nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

d. Creating Arrays from Scratch

Khusus untuk array yang lebih besar, akan lebih efisien untuk membuat array dari awal menggunakan routines dibangun ke dalam NumPy. Berikut beberapa contohnya:

In [131]:
#Membuat larik bilangan bulat 10 panjang yang diisi dengan nol 
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [132]:
#Membuat array floating-point 3x5 yang diisi dengan 1s 
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [133]:
#Membuat array 3x5 dengan isi 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [134]:
#Buat array yang diisi dengan urutan linier
#Mulai dari 0, berakhir pada 20, step = 2
#(ini mirip dengan fungsi range () bawaan) 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [135]:
#Membuat array dengan lima nilai yang jaraknya sama antara 0 dan 1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [136]:
#Membuat array 3x3 yang terdistribusi secara merata
#nilai random dari 0 dan 1
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [137]:
#Memuat array 3x3 dengan nilai acak yang terdistribusi normal
#dengan mean 0 dan deviasi standar 1 
np.random.normal(0, 1, (3, 3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [138]:
#Membuat array 3x3 dari bilangan bulat acak dalam interval [0, 10) 
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [139]:
#membuat matriks identitas 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
#Membuat array tiga bilangan bulat yang tidak diinisialisasi
#Nilai akan menjadi apa pun yang terjadi sudah ada pada saat itu
#lokasi memori 
np.empty(3)

array([1., 1., 1.])

e. NumPy Standard Data Types

saat membangun sebuah array, Kita dapat menentukannya menggunakan string / menggunakan associated numpy object

In [141]:
#String
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [142]:
#associated numpy object
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

2) The Basics of NumPy Arrays

a. Numpy Array Attributes

Kitaakan menggunakan Generator nomor acak NumPy, yang akan kita seed dengan nilai yang ditetapkan untuk memastikan bahwa array acak yang sama dibuat setiap kali kode ini dijalankan:

In [143]:
import numpy as np
np.random.seed(0) #seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [144]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [145]:
#atribut dtype
print("dtype:", x3.dtype)

dtype: int64


In [146]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


b. Array Indexing: Accessing Single Elements

Dalam array satu dimensi, Anda dapat mengakses dengan menentukan indeks yang diinginkan dalam tanda kurung siku

In [147]:
x1

array([5, 0, 3, 3, 7, 9])

In [148]:
x1[0]

5

In [149]:
x1[4]

7

In [150]:

#Untuks pengindeksan dari akhir array gunakan -
x1[-1]

9

In [151]:

x1[-2]

7


Dalam array multidimensi, Kita mengakses item menggunakan tupel yang dipisahkan koma dari indeks:

In [152]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [153]:
x2[0, 0]

3

In [154]:
x2[2, 0]

1

In [155]:
x2[2, -1]

7


Kita dapat mengubah nilai menggunakan salah satu notasi indeks di atas

In [156]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

array NumPy memiliki tipe tetap. Ini berarti,misalnya, jika kita mencoba memasukkan nilai floating-point ke array integer, file nilai akan terpotong secara diam-diam

In [157]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

c. Array Slicing: Accessing Subarrays

cara mengakses subarray dalam satu dimensi dan dalam berbagai dimensi.

one-dimensional subarrays

In [158]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [160]:

x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [161]:
x[4:7] # middle subarray

array([4, 5, 6])

In [162]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [163]:

x[1::2] # every other element, starting at index 1


array([1, 3, 5, 7, 9])

In [164]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [165]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

x[5::-2] # reversed every other from index 5

In [166]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [167]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [168]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [169]:
#dimensi subarray bahkan dapat dibalik bersama: 
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])


Accessing array rows and columns

Untuk mengakses single baris atau kolom dari sebuah array.Kita dapat melakukan ini dengan menggabungkan pengindeksan dan slicing, menggunakan slice kosong yang ditandai dengan satu titik dua (:):



In [170]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [171]:
print(x2[0, :]) # first row of x2

[12  5  2  4]


In [172]:
#dalam kasus akses rroq, slice kosong dapat dihilangkan untuk sintaks yang lebih ringkas:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


Subarrays as no-copy views

irisan array mengembalikan tampilan daripada salinan data array. Ini adalah salah satu area di mana NumPy mengiris array berbeda dari slicing daftar Python:

In [173]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [176]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [180]:
x2_sub_copy[0, 0] = 99
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [181]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Creating copies of arrays

salin data dalam array atau subarray. Ini dapat dilakukan paling mudah dengan file copy () metode:

In [182]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [185]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [184]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]



Reshaping of Arrays

Jenis operasi lain yang berguna adalah pembentukan kembali array. Cara paling fleksibel dari melakukan ini dengan metode reshape (). Misalnya, jika ingin meletakkan nomor bers 1 hingga 9 dalam kisi 3 × 3, Kita dapat melakukan hal berikut:

In [186]:

grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



Pola pembentukan kembali lainnya adalah konversi array satu dimensi menjadi matriks baris atau kolom dua dimensi.Kita dapat melakukan ini dengan bentuk ulang metode, atau lebih mudah dengan menggunakan kata kunci sumbu baru dalam operasi:

In [198]:
x = np.array([1, 2, 3])
 # row vector via reshape
 x.reshape((1, 3))

IndentationError: ignored

In [188]:
#row vector via newaxis
x[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [199]:
# column vector via reshape
x.reshape((3, 1))

ValueError: ignored

In [196]:
# column vector via newaxis
x[:, np.newaxis]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Array Concatenation and Splitting

Menggabungkan beberapa array menjadi satu, dan sebaliknya membagi satu array menjadi beberapa array.

Concatenation of arrays

Penggabungan, atau penggabungan dua array di NumPy, dilakukan terutama melalui rutinitas np.concatenate, np.vstack, dan np.hstack. np.concatenate mengambil tupel atau daftar array sebagai argumen pertamanya

In [200]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [201]:
#menggabungkan lebih dari dua array sekaligus
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [204]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

In [203]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [205]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])


Untuk bekerja dengan array dengan dimensi campuran, akan lebih jelas menggunakan np.vstack Fungsi (stack vertikal) dan np.hstack (stack horizontal):

In [206]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [207]:
# horizontally stack the arrays
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Splitting of arrays

Kebalikan dari penggabungan adalah pemisahan, yang diimplementasikan oleh fungsi np.split, np.hsplit, dan np.vsplit. Untuk masing-masing ini, kita dapat memberikan daftar indeks memberikan poin perpecahan:

In [208]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]



Perhatikan bahwa titik pisah N mengarah ke N + 1 subarray. Fungsi terkait np.hsplit dan np.vsplit serupa:

In [209]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [211]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
